### ISSUE TITLE
[Task] CI fails to download `cryostat-core` dependency

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-agent#126]
For example:

https://github.com/cryostatio/cryostat-agent/pull/125
(https://github.com/cryostatio/cryostat-agent/actions/runs/5070291951/jobs/9105123984?pr=125)
![image](https://github.com/cryostatio/cryostat-agent/assets/3787464/e622c1a7-58d1-4a12-957e-75da68a3edb2)

The project's `pom.xml` is configured to search the GitHub Maven Packages repository, but authentication is failing.

https://github.com/cryostatio/cryostat-agent/blob/8d2eb414029c436efde2c9b2d0a308d0dad59d66/pom.xml#L13

The CI workflow does have a step that is supposed to set up the Maven `settings.xml` that provides the credentials however:

https://github.com/cryostatio/cryostat-agent/blob/8d2eb414029c436efde2c9b2d0a308d0dad59d66/.github/workflows/ci.yaml#L32

And the same or very similar configuration is used in the main Cryostat repository, which works and is able to download the `cryostat-core` dependency:

https://github.com/cryostatio/cryostat/blob/2b0cd5adacf8f928f8666f36663b0a5b31e0e76b/.github/workflows/ci-jobs.yml#L53

**Comment by ebaron** [comment]
This is the `pull_request_target` issue right?

**Comment by andrewazores** [comment]
I think so, yes. The secret is probably unreadable to the actions runners with the current configuration so the authentication fails because the password/token being provided in the Maven `settings.xml` would be an empty string.

**Comment by andrewazores** [comment]
(it's frustrating that GitHub Packages *still* doesn't allow unauthenticated downloads)

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat-agent/pull/149#issuecomment-1593069867

**Comment by andrewazores** [comment]
It looks like the CI job also needs to (re)trigger when PRs are labelled or unlabelled:

https://github.com/cryostatio/cryostat-agent/pull/150

This PR is failing because the runner thinks `safe-to-test` is missing, but it is actually there, and removing/re-adding the label doesn't trigger the job again, nor does it seem to be able to refresh its state on a re-run.

https://github.com/cryostatio/cryostat-agent/blob/f0744e9766a5fac180c125489907c9726a698fdc/.github/workflows/ci.yaml#L10

vs

https://github.com/cryostatio/cryostat/blob/main/.github/workflows/pr-ci.yml#L13

**Comment by maxcao13** [comment]
Sounds good, I'll redo it today.

**Comment by maxcao13** [comment]
Fixed with #151, hopefully.

**Comment by andrewazores** [comment]
Looks good:
https://github.com/cryostatio/cryostat-agent/actions/runs/5292782560/jobs/9580084638?pr=150
